server.port=8072
eureka.instance.preferIpAddress = true 
eureka.client.registerWithEureka = true
eureka.client.fetchRegistry = true
eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka
spring.cloud.gateway.discovery.locator.lowerCaseServiceId=true

spring.cloud.gateway.routes[0].predicates=Path=/zabalburu/productos/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/zabalburu/productos/?(?<remaining>.*) ,/productos/${remaining}
spring.cloud.gateway.routes[0].uri=lb://PRODUCTOS
spring.cloud.gateway.routes[1].predicates=Path=/zabalburu/categorias/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/zabalburu/categorias/?(?<remaining>.*) ,/categorias/${remaining}
spring.cloud.gateway.routes[1].uri=lb://PRODUCTOS
spring.cloud.gateway.routes[2].predicates=Path=/zabalburu/clientes/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/zabalburu/clientes/?(?<remaining>.*) ,/clientes/${remaining}
spring.cloud.gateway.routes[2].uri=lb://CLIENTES

#spring.cloud.gateway.routes[0].predicates=Path=/zabalburu/**
#spring.cloud.gateway.routes[0].filters[0]=RewritePath=/zabalburu/?(?<remaining>.*) ,/${remaining}
#spring.cloud.gateway.routes[0].uri=lb://PRODUCTOS

spring.sleuth.sampler.probability=1
spring.zipkin.base-url=http://zipkin:9411
